RSpec compatibility improvements
* Primary test data path has been changed from features/test_data/ to config/test_data/
* No longer throws a 'NoMethodError: undefined method 'World' for main:Object' error when using RSpec.